#!/bin/bash

docker build -t keepalived .
docker run -d -it \
       --mount type=bind,source=./tests/options.json,target=/data/options.json \
       --mount type=bind,source=./tests/test-keepalived.conf,target=/etc/keepalived/keepalived.conf \
       keepalived
