# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armhf: "ghcr.io/home-assistant/armhf-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
  i386: "ghcr.io/home-assistant/i386-base:3.21"
labels:
  org.opencontainers.image.title: "Keepalived"
  org.opencontainers.image.description: "Keepalived for Home Assistant"
  org.opencontainers.image.source: "https://github.com/rsnodgrass/hassio-addons"
  org.opencontainers.image.licenses: "MIT License"
args:
  TEMPIO_VERSION: "2024.11.2"
