arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
# - x86-64
boot: auto
description: Keepalived Home Assistant Add-On (wraps Docker container shawly/docker-keepalived)
host_network: true
#image: rsnodgrass/hassio-addons/keepalived/{arch}
image: "ghcr.io/home-assistant/{arch}-keepalived-addon"
name: keepalived
hassio_api: true
options:
  check_ip: 192.168.1.231
  check_port: '53'
  interface: eth0
  priority: '150'
  router_id: '51'
  tz: 'Etc/UTC'
  virtual_ips: 192.168.1.231
  virtual_mask: '24'
schema:
  check_ip: str
  check_port: int
  interface: str
  priority: str
  router_id: str
  tz: str
  virtual_ips: str
  virtual_mask: int
slug: keepalived
startup: system
version: 0.0.1
privileged:
  - NET_ADMIN
