name: Keepalived
slug: keepalived
version: 0.0.3
description: >-
  "Keepalived HA add-on to support Virtual Router Redundancy Protocol (VRRP) for load balancing and high availability (e.g. for high-availability DNS server cluster)."
url: https://github.com/rsnodgrass/hassio-addons/tree/master/keepalived

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

boot: auto
startup: system
privileged:
  - NET_ADMIN
host_network: true # required since keepalived config from user may specify many ports
hassio_api: true
init: false

map:
  # mount /addon_configs/keepalived to /etc/keepalived (instead of default /config)
  #  ... this will allow /etc/keepalived/keepalived.conf custom configuration
  - type: addon_config
    read_only: False
    path: /etc/keepalived
  # enable copying custom /homeassistant_config/keepalived.conf to /etc/keepalived/keepalived.conf
  - type: homeassistant_config

# FIXME: remove all these options (since they should be keepalived.conf instead) ... leave TZ in place
options:
  KEEPALIVED_VRID: 53
  KEEPALIVED_VIRTUAL_IP: 192.168.1.53
  KEEPALIVED_VIRTUAL_MASK: 24
  KEEPALIVED_CHECK_PORT: 53
  TZ: 'Etc/UTC'
#  custom_config: use /etc/keepalived/keepalived.config or /config/keepalived.conf or /addon_configs/keepalived/keepalived.conf

schema:
  KEEPALIVED_VIRTUAL_IP: str
  KEEPALIVED_VIRTUAL_MASK: int(,32)
  KEEPALIVED_CHECK_PORT: port
  KEEPALIVED_VRID: int(,255)
  TZ: str
