arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
description: Keepalived Home Assistant Add-On (wraps Docker container shawly/docker-keepalived)
host_network: true
#image: rsnodgrass/hassio-addons/keepalived/{arch}
#image: "ghcr.io/home-assistant/{arch}-keepalived-addon"
name: keepalived
hassio_api: true
init: false
options:
  KEEPALIVED_INTERFACE: eth0
  KEEPALIVED_VIRTUAL_IP: 192.168.1.231
  KEEPALIVED_VIRTUAL_MASK: 24
  KEEPALIVED_CHECK_IP: any
  KEEPALIVED_CHECK_PORT: 53
  KEEPALIVED_VRID: 51
  TZ: 'Etc/UTC'
schema:
  KEEPALIVED_INTERFACE: str
  KEEPALIVED_VIRTUAL_IP: str
  KEEPALIVED_VIRTUAL_MASK: int
  KEEPALIVED_CHECK_IP: str
  KEEPALIVED_CHECK_PORT: int
  KEEPALIVED_VRID: int
  TZ: str
slug: keepalived
startup: system
version: 0.0.3
privileged:
  - NET_ADMIN
