name: "Keepalived"
slug: keepalived
version: "1.0.0"
description: >-
  Operate highly available services (e.g. DNS) using the Virtual Router Redundancy Protocol (VRRP)
url: "https://github.com/rsnodgrass/hassio-addons/tree/master/keepalived"

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

startup: system
boot: auto
init: false
privileged:
  - NET_ADMIN
host_network: true # required since keepalived config from user may specify many ports

hassio_api: true
homeassistant: 2024.8.1  # requires the map type/path config.yaml feature

map:
  # mount /addon_configs/keepalived to /etc/keepalived (instead of default /config)
  #  ... this will allow /etc/keepalived/keepalived.conf custom configuration
  - type: addon_config
    read_only: False
    path: /etc/keepalived
  # enable copying custom /homeassistant/keepalived.conf to /etc/keepalived/keepalived.conf
  - type: homeassistant_config
    path: /homeassistant

options:
  TZ: 'Etc/UTC'

schema:
  TZ: str
