arch:
- aarch64
#- amd64
- arm64
- armv7
#- armhf
#- x86-64
#- i386
boot: auto
description: Keepalived Home Assistant Add-On (wraps Docker container shawly/docker-keepalived)
host_network: true
#image: rsnodgrass/hassio-addons/keepalived/{arch}
name: keepalived
hassio_api: true
options:
  check_ip: 192.168.1.231
  check_port: '53'
  interface: eth0
  priority: '150'
  router_id: '51'
  tz: 'Etc/UTC'
  virtual_ips: 192.168.1.231
  virtual_mask: '24'
privileged:
  - NET_ADMIN
schema:
  check_ip: str
  check_port: int
  interface: str
  priority: str
  router_id: str
  tz: str
  virtual_ips: str
  virtual_mask: int
slug: keepalived
startup: system
version: 0.0.1
