arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
description: Keepalived Home Assistant Add-On (wraps Docker container shawly/docker-keepalived)
host_network: true
#image: rsnodgrass/hassio-addons/keepalived/{arch}
#image: "ghcr.io/home-assistant/{arch}-keepalived-addon"
name: keepalived
hassio_api: true
options:
  interface: eth0
  virtual_ip: 192.168.1.231
  virtual_mask: '24'
  check_ip: 192.168.1.231
  check_port: '53'
  router_id: '51'
  tz: 'Etc/UTC'
schema:
  interface: str
  virtual_ip: str
  virtual_mask: int
  check_ip: str
  check_port: int
  router_id: str
  tz: str
slug: keepalived
startup: system
version: 0.0.1
privileged:
  - NET_ADMIN
