name: keepalived
version: 0.0.3
description: Keepalived HA add-on to support Virtual Router Redundancy Protocol (VRRP) for load balancing and high availability (e.g. for high-availability DNS server cluster).
url: https://github.com/rsnodgrass/hassio-addons/tree/master/keepalived

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
host_network: true
#image: rsnodgrass/hassio-addons/keepalived/{arch}
#image: "ghcr.io/home-assistant/{arch}-keepalived-addon"
hassio_api: true
init: false
options:
  KEEPALIVED_INTERFACE: end0
  KEEPALIVED_VRID: 53
  KEEPALIVED_VIRTUAL_IP: 192.168.1.53
  KEEPALIVED_VIRTUAL_MASK: 24
  KEEPALIVED_CHECK_IP: any
  KEEPALIVED_CHECK_PORT: 53
  TZ: 'Etc/UTC'
schema:
  KEEPALIVED_INTERFACE: str
  KEEPALIVED_VIRTUAL_IP: str
  KEEPALIVED_VIRTUAL_MASK: int(,32)
  KEEPALIVED_CHECK_IP: str
  KEEPALIVED_CHECK_PORT: port
  KEEPALIVED_VRID: int(,255)
  TZ: str
slug: keepalived
startup: system
privileged:
  - NET_ADMIN
